In [1]:
import torch
from torch.autograd import Variable

In [2]:
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [3]:
var.requires_grad

False

In [4]:
var.requires_grad_()

tensor([9.], requires_grad=True)

In [5]:
w1 = Variable(torch.FloatTensor([3]), requires_grad = True)
w2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [6]:
w1

tensor([3.], requires_grad=True)

In [7]:
w2

tensor([7.], requires_grad=True)

In [9]:
result_var = w1 * w2
result_var

tensor([21.], grad_fn=<MulBackward0>)