In [1]:
import torch

In [7]:
tensor1 = torch.tensor([[1., 2., 3.],
                        [4., 5., 6.]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
tensor2 = torch.tensor([[7., 8., 9.],
                        [10., 11., 12.]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

Every tensor created in PyTorch will have the <b>requires_grad</b> property.
When true this <b>tracks computations for a tensor in the forward phase</b>
and will <b>calculate gradients for this tensor in the backward phase</b>.

In [9]:
tensor1.requires_grad

False

In [10]:
tensor2.requires_grad

False

In [11]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [13]:
print(tensor1.grad)

None


In [14]:
print(tensor1.grad_fn)

None


In [15]:
output_tensor = tensor1 * tensor2

In [16]:
output_tensor.requires_grad

True

In [17]:
print(output_tensor.grad)

None


C:\Users\longqinsi\AppData\Local\Temp\ipykernel_16272\1906321212.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:491.)
  print(output_tensor.grad)


In [18]:
print(output_tensor.grad_fn)

In [19]:
output_tensor2 = (tensor1 * tensor2).mean()
print(output_tensor2.grad_fn)

In [21]:
output_tensor2.backward()

In [22]:
print(tensor1.grad)

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [23]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [24]:
new_tensor = tensor1 * 3

In [25]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [26]:
with torch.no_grad():
    new_tensor = tensor1 * 3
    print('new_tensor = ', new_tensor)
    print('requires_grad for tensor1 = ', tensor1.requires_grad)
    print('requires_grad for tensor2 = ', tensor2.requires_grad)
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor1 =  True
requires_grad for tensor2 =  False
requires_grad for new_tensor =  False


In [27]:
def calculate(t):
    return t * 2

In [28]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [29]:
result_tensor = calculate(tensor1)

result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [30]:
result_tensor.requires_grad

True

In [31]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)

result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [32]:
result_tensor_no_grad.requires_grad

False

In [33]:
with torch.no_grad():
    new_tensor_no_grad = tensor1 * 3
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    with torch.enable_grad():
        new_tensor_grad = tensor1 * 3
        print('new_tensor_grad = ', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [34]:
tensor_one = torch.tensor([[1.0, 2.0],
                           [3.0, 4.0]], requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [35]:
tensor_two = torch.Tensor([[5.0, 6.0],
                       [7.0, 8.0]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [36]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [37]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [40]:
final_tensor.requires_grad

True

In [41]:
print(tensor_one.grad)

None


In [42]:
final_tensor.backward()

In [43]:
tensor_one.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [44]:
tensor_two.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

detach() Returns a new tensor detached from the current computation graph - will always have requires_grad=False

In [46]:
detached_tensor = tensor_one.detach()

detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [47]:
mean_tensor = (tensor_one + detached_tensor).mean()
mean_tensor.backward()

In [48]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [51]:
print(detached_tensor.grad)

None
