In [2]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
W = torch.randn(6)

x = torch.tensor([10.0, 10.0, 10.0, 10.0, 10.0, 10.0])

b = torch.tensor(3)

In [4]:
W

tensor([-0.0970,  0.1345, -0.0530,  0.2260, -1.0445, -1.0370])

In [5]:
y = W*x+b

In [6]:
y

tensor([ 2.0298,  4.3451,  2.4698,  5.2605, -7.4452, -7.3702])

In [7]:
W*x

tensor([ -0.9702,   1.3451,  -0.5302,   2.2605, -10.4452, -10.3702])

In [8]:
b

tensor(3)

In [9]:
W1 = torch.tensor(6)
W2 = torch.tensor(6)
W3 = torch.tensor(6)

x1 = torch.tensor([2, 2, 2])
x2 = torch.tensor([3, 3, 3])
x3 = torch.tensor([4, 4, 4])

b = torch.tensor(10)

In [10]:
W1, W2, W3

(tensor(6), tensor(6), tensor(6))

In [11]:
intermediate_value = W1 * x1 + W2 * x2
intermediate_value

tensor([30, 30, 30])

In [12]:
final_value = W1*x1 + W2*x2 + W3*x3 + b
final_value

tensor([64, 64, 64])

In [13]:
import hiddenlayer as hl

In [14]:
x_train = np.array ([[1.7], [2.5], [5.5], [7.9], [8.8],
                     [2.4],[2.4], [8.89], [5], [4.4]],
                    dtype = np.float32)

y_train = np.array ([[1.9], [2.68], [4.22], [8.19], [9.69],
                     [3.4],[2.6], [8.8], [5.6], [4.7]],
                    dtype = np.float32)

In [15]:
X_train = torch.tensor(x_train)
Y_train = torch.tensor(y_train)

X_train.shape

torch.Size([10, 1])

In [16]:
inp = 1
out = 1

hid = 100

In [17]:
model1 = torch.nn.Sequential(torch.nn.Linear(inp, hid),
                             torch.nn.Linear(hid, out))

In [20]:
torch.onnx.export(model1, X_train, "model.onnx", input_names=["input"], output_names=["output"])

================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================



In [ ]:
from torch.utils.tensorboard import SummaryWriter
